import type {
  AgentProfile,
  AgentListing,
  AgentBuilding,
  MarketStats,
  AgentTestimonial,
  NeighbourhoodSummary,
  NeighbourhoodDetail,
  MarketReport,
  AgentPage,
  AgentAward,
  AgentMedia,
  TeamMember,
  NewsPost,
  OpenHouseItem,
  PriceMatrix,
} from './types'

export const RANDY_FALLBACK: AgentProfile = {
  id: 1,
  slug: 'randy',
  name: 'Randy Dyck',
  brokerage: 'Exp Realty',
  phone: '604-807-4366',
  email: null,
  bio: "Randy Dyck has been helping buyers and sellers navigate the South Surrey, White Rock, and Cloverdale markets for over two decades. Known for his deep neighbourhood knowledge, straightforward advice, and relentless follow-through, Randy brings real data and real candour to every conversation.\n\nWhether you're upsizing into a family home in South Surrey, purchasing your first condo in Cloverdale, or selling a long-held White Rock property, Randy is not interested in telling you what you want to hear — he's interested in getting you the best outcome.\n\nRandy lives in the communities he serves and raises his family here. That's not a tagline — it's the reason he cares about every transaction.",
  photo_path: 'https://southsurreywhiterock.com/images/randy-headshot-v3.webp',
  logo_path: null,
  license_number: 'R4568290',
  theme_slug: 'classic-dark',
  theme_color: '#111111',
  primary_bg_color: '#111111',
  brand_text_color: '#ffffff',
  status: 'active',
  settings: {
    custom_domain: 'southsurreywhiterock.com',
    ga4_id: null,
    fb_pixel_id: null,
    intro_video_url: null,
    social_links: null,
    featured_listing_ids: null,
    notification_email: null,
    notification_phone: null,
    fub_enabled: false,
    ghl_enabled: false,
    ghl_api_key: null,
    lead_routing: null,
    seo_noindex: true,
    subarea_whitelist: null,
    guide_name: 'South Surrey & White Rock Homes for Sale',
    photo_fallback_url: null,
    favicon_url: null,
    designation: null,
    team_members: null,
    achievements: null,
    co_agent_achievements: null,
  },
  features: {
    market_intelligence: true,
  },
}

export const TRICITY_FALLBACK: AgentProfile = {
  id: 2,
  slug: 'tricity',
  name: 'Nav Shahram',
  brokerage: 'Exp Realty',
  phone: '',
  email: null,
  bio: 'Nav Shahram and Reza Hedayat are experienced REALTORS® serving the Tri-Cities — Coquitlam, Port Coquitlam, and Port Moody. Browse active MLS® listings, get a free home evaluation, and connect with a trusted local expert.',
  photo_path: null,
  logo_path: null,
  license_number: null,
  theme_slug: 'classic-dark',
  theme_color: '#111111',
  primary_bg_color: '#111111',
  brand_text_color: '#ffffff',
  status: 'active',
  settings: {
    custom_domain: 'suburbia.ca',
    ga4_id: null,
    fb_pixel_id: null,
    intro_video_url: null,
    social_links: null,
    featured_listing_ids: null,
    notification_email: null,
    notification_phone: null,
    fub_enabled: false,
    ghl_enabled: false,
    ghl_api_key: null,
    lead_routing: null,
    seo_noindex: false,
    subarea_whitelist: null,
    guide_name: null,
    photo_fallback_url: null,
    favicon_url: null,
    designation: null,
    team_members: null,
    achievements: null,
    co_agent_achievements: null,
  },
  features: {
    market_intelligence: true,
  },
}

export const SHARENE_FALLBACK: AgentProfile = {
  id: 3,
  slug: 'sharene',
  name: 'Sharene Shuster',
  brokerage: 'Exp Realty',
  phone: '',
  email: null,
  bio: 'Sharene Shuster is an experienced REALTOR® serving Vancouver and surrounding neighbourhoods. Browse active MLS® listings, get a free home evaluation, and connect with a trusted local expert.',
  photo_path: null,
  logo_path: null,
  license_number: null,
  theme_slug: 'classic-dark',
  theme_color: '#111111',
  primary_bg_color: '#111111',
  brand_text_color: '#ffffff',
  status: 'active',
  settings: {
    custom_domain: 'shareneshuster.com',
    ga4_id: null,
    fb_pixel_id: null,
    intro_video_url: null,
    social_links: null,
    featured_listing_ids: null,
    notification_email: null,
    notification_phone: null,
    fub_enabled: false,
    ghl_enabled: false,
    ghl_api_key: null,
    lead_routing: null,
    seo_noindex: false,
    subarea_whitelist: null,
    guide_name: null,
    photo_fallback_url: null,
    favicon_url: null,
    designation: null,
    team_members: null,
    achievements: null,
    co_agent_achievements: null,
  },
  features: {
    market_intelligence: true,
  },
}

export const AGENT_FALLBACKS: Record<string, AgentProfile> = {
  randy: RANDY_FALLBACK,
  tricity: TRICITY_FALLBACK,
  sharene: SHARENE_FALLBACK,
}

export const FALLBACK_LISTINGS: AgentListing[] = [
  { id: 1001, mls_no: 'R2900001', address: '312 - 15918 26th Ave', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Active', list_price: 699000, sold_price: null, beds: 2, baths: 2, sqft: 1048, photo_url: null, type: 'Apartment', style: 'Inside Unit', slug: 'r2900001', dom: 14 },
  { id: 1002, mls_no: 'R2900002', address: '55 - 3400 Rosemary Heights Dr', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Active', list_price: 1149000, sold_price: null, beds: 3, baths: 2.5, sqft: 1682, photo_url: null, type: 'Townhouse', style: 'End Unit', slug: 'r2900002', dom: 7 },
  { id: 1003, mls_no: 'R2900003', address: '1644 140th St', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Active', list_price: 1899000, sold_price: null, beds: 4, baths: 3, sqft: 2820, photo_url: null, type: 'House', style: 'Two Storey', slug: 'r2900003', dom: 21 },
  { id: 1004, mls_no: 'R2900004', address: '204 - 1420 Johnston Rd', city: 'White Rock', subarea: null, status: 'Active', list_price: 589000, sold_price: null, beds: 1, baths: 1, sqft: 682, photo_url: null, type: 'Apartment', style: 'Corner Unit', slug: 'r2900004', dom: 30 },
  { id: 1005, mls_no: 'R2900005', address: '418 - 15357 17A Ave', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Active', list_price: 748800, sold_price: null, beds: 2, baths: 2, sqft: 1102, photo_url: null, type: 'Apartment', style: 'Inside Unit', slug: 'r2900005', dom: 5 },
  { id: 1006, mls_no: 'R2900006', address: '12 - 12633 No. 2 Rd', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Active', list_price: 1249000, sold_price: null, beds: 3, baths: 2, sqft: 1450, photo_url: null, type: 'Townhouse', style: 'Inside Unit', slug: 'r2900006', dom: 11 },
  { id: 1007, mls_no: 'R2900007', address: '14837 36A Ave', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Active', list_price: 2299000, sold_price: null, beds: 5, baths: 4, sqft: 3800, photo_url: null, type: 'House', style: 'Two Storey w/Bsmt', slug: 'r2900007', dom: 42 },
  { id: 1008, mls_no: 'R2900008', address: '317 - 15850 26th Ave', city: 'Surrey', subarea: 'Grandview Heights', status: 'Active', list_price: 629000, sold_price: null, beds: 2, baths: 2, sqft: 904, photo_url: null, type: 'Apartment', style: 'Inside Unit', slug: 'r2900008', dom: 18 },
  { id: 1009, mls_no: 'R2900009', address: '82 - 16138 28th Ave', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Active', list_price: 899000, sold_price: null, beds: 3, baths: 2.5, sqft: 1558, photo_url: null, type: 'Townhouse', style: 'Inside Unit', slug: 'r2900009', dom: 9 },
]

export const FALLBACK_SOLD_LISTINGS: AgentListing[] = [
  { id: 2001, mls_no: 'R2880001', address: '508 - 15188 29A Ave', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Sold', list_price: 679000, sold_price: 665000, beds: 2, baths: 2, sqft: 985, photo_url: null, type: 'Apartment', style: 'Inside Unit', slug: 'r2880001', dom: 8 },
  { id: 2002, mls_no: 'R2880002', address: '21 - 2418 156th St', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Sold', list_price: 1099000, sold_price: 1075000, beds: 3, baths: 2.5, sqft: 1620, photo_url: null, type: 'Townhouse', style: 'End Unit', slug: 'r2880002', dom: 14 },
  { id: 2003, mls_no: 'R2880003', address: '1828 152nd St', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Sold', list_price: 1749000, sold_price: 1700000, beds: 4, baths: 3, sqft: 2540, photo_url: null, type: 'House', style: 'Two Storey', slug: 'r2880003', dom: 25 },
  { id: 2004, mls_no: 'R2880004', address: '301 - 1526 George St', city: 'White Rock', subarea: null, status: 'Sold', list_price: 559000, sold_price: 545000, beds: 1, baths: 1, sqft: 710, photo_url: null, type: 'Apartment', style: 'Corner Unit', slug: 'r2880004', dom: 19 },
  { id: 2005, mls_no: 'R2880005', address: '107 - 15400 29A Ave', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Sold', list_price: 724900, sold_price: 715000, beds: 2, baths: 2, sqft: 1080, photo_url: null, type: 'Apartment', style: 'Inside Unit', slug: 'r2880005', dom: 11 },
  { id: 2006, mls_no: 'R2880006', address: '47 - 15588 36A Ave', city: 'Surrey', subarea: 'South Surrey White Rock', status: 'Sold', list_price: 1188000, sold_price: 1155000, beds: 3, baths: 2.5, sqft: 1495, photo_url: null, type: 'Townhouse', style: 'Inside Unit', slug: 'r2880006', dom: 6 },
]

export const FALLBACK_BUILDINGS: AgentBuilding[] = [
  { id: 'b001', name: 'Azure', slug: 'azure-south-surrey', city: 'Surrey', subarea: 'South Surrey White Rock', year_built: 2019, units: 220, levels: 12, strata_no: null, street_no: '15268', street_name: '18', street_type: 'Ave', address: '15268 18 Ave, Surrey', postal_code: 'V4A 0A1', status: 'Completed', title_to_land: 'Freehold Strata', photo_url: null, min_price: 649000, max_price: 1150000, active_listings: 8 },
  { id: 'b002', name: 'The Heights', slug: 'the-heights-grandview', city: 'Surrey', subarea: 'Grandview Heights', year_built: 2021, units: 148, levels: 8, strata_no: null, street_no: '16458', street_name: '23A', street_type: 'Ave', address: '16458 23A Ave, Surrey', postal_code: 'V3Z 0Y2', status: 'Completed', title_to_land: 'Freehold Strata', photo_url: null, min_price: 589000, max_price: 985000, active_listings: 5 },
  { id: 'b003', name: 'The Strand', slug: 'the-strand-white-rock', city: 'White Rock', subarea: null, year_built: 2018, units: 80, levels: null, strata_no: null, street_no: '1485', street_name: 'Johnston', street_type: 'Rd', address: '1485 Johnston Rd, White Rock', postal_code: 'V4B 3Z4', status: 'Completed', title_to_land: 'Freehold Strata', photo_url: null, min_price: 549000, max_price: 899000, active_listings: 3 },
  { id: 'b004', name: 'Springwood', slug: 'springwood-south-surrey', city: 'Surrey', subarea: 'South Surrey White Rock', year_built: 2016, units: 168, levels: null, strata_no: null, street_no: '15188', street_name: '29A', street_type: 'Ave', address: '15188 29A Ave, Surrey', postal_code: 'V4P 0E6', status: 'Completed', title_to_land: 'Freehold Strata', photo_url: null, min_price: 559000, max_price: 799000, active_listings: 6 },
  { id: 'b005', name: 'Morgan Creek Estates', slug: 'morgan-creek-estates', city: 'Surrey', subarea: 'South Surrey White Rock', year_built: 2022, units: 195, levels: 14, strata_no: null, street_no: '3535', street_name: '146A', street_type: 'St', address: '3535 146A St, Surrey', postal_code: 'V3Z 0R8', status: 'Completed', title_to_land: 'Freehold Strata', photo_url: null, min_price: 699000, max_price: 1299000, active_listings: 11 },
  { id: 'b006', name: 'White Rock Waterfront', slug: 'white-rock-waterfront', city: 'White Rock', subarea: null, year_built: 2020, units: 96, levels: null, strata_no: null, street_no: '15165', street_name: 'Marine', street_type: 'Dr', address: '15165 Marine Dr, White Rock', postal_code: 'V4B 1C6', status: 'Completed', title_to_land: 'Freehold Strata', photo_url: null, min_price: 798000, max_price: 1599000, active_listings: 4 },
]

export const FALLBACK_STATS: MarketStats = {
  active_count: 312,
  avg_list_price: 1048000,
  sold_last_30_days: 87,
  avg_sold_price: 998000,
  avg_dom: 18,
}

export const FALLBACK_TESTIMONIALS: AgentTestimonial[] = [
  { id: 1, name: 'Sandra M.', text: "Randy sold our White Rock condo in 9 days — over asking. He told us exactly what it was worth, we listed at that number, and it was done. No drama, no guessing games. Outstanding.", rating: 5, source: 'Google', source_url: null, date: '2024-10-14' },
  { id: 2, name: 'James & Heather L.', text: "We were relocating from Calgary and bought our South Surrey home sight unseen (mostly). Randy did a video walkthrough, gave us an honest assessment of every issue he saw, and negotiated hard on our behalf. Couldn't be happier.", rating: 5, source: 'Google', source_url: null, date: '2024-08-22' },
  { id: 3, name: 'Kevin T.', text: "Third time working with Randy. He knows this market better than anyone — the micro-differences between Morgan Creek and Grandview Heights, what drives prices on one street vs. the next. Genuinely useful, not just a cheerleader.", rating: 5, source: 'Google', source_url: null, date: '2024-06-05' },
  { id: 4, name: 'Michelle O.', text: "Sold my parents' home in White Rock after they passed. Randy handled the whole process with so much care and professionalism. He made a very difficult time much easier.", rating: 5, source: 'Google', source_url: null, date: '2024-04-18' },
  { id: 5, name: 'Chris & Dana P.', text: "Randy told us to wait three months before listing — the market was about to shift, he said. We waited. Listed at the right time, sold in 5 days over asking. The patience paid off.", rating: 5, source: 'Google', source_url: null, date: '2024-01-30' },
]

export const FALLBACK_NEIGHBOURHOODS: NeighbourhoodSummary[] = [
  { name: 'South Surrey White Rock', city: 'Surrey', subarea: 'South Surrey White Rock', slug: 'south-surrey-white-rock', active_count: 184 },
  { name: 'Grandview Heights', city: 'Surrey', subarea: 'Grandview Heights', slug: 'grandview-heights', active_count: 56 },
  { name: 'Morgan Creek', city: 'Surrey', subarea: 'Morgan Creek', slug: 'morgan-creek', active_count: 38 },
  { name: 'Cloverdale', city: 'Surrey', subarea: 'Cloverdale BC', slug: 'cloverdale-bc', active_count: 47 },
  { name: 'White Rock', city: 'White Rock', subarea: null, slug: 'white-rock', active_count: 63 },
]

export const FALLBACK_MARKET_REPORT: MarketReport = {
  overall: { active: 312, sold_30d: 87, avg_sold_price: 998000, avg_dom: 18, absorption_rate: 27.9, market_type: 'sellers' },
  by_type: [
    { type: 'Apartment', active: 128, sold_30d: 41, avg_sold_price: 642000, avg_dom: 15, absorption_rate: 32.0, market_type: 'sellers' },
    { type: 'Townhouse', active: 84, sold_30d: 28, avg_sold_price: 1045000, avg_dom: 16, absorption_rate: 33.3, market_type: 'sellers' },
    { type: 'House', active: 100, sold_30d: 18, avg_sold_price: 1789000, avg_dom: 27, absorption_rate: 18.0, market_type: 'balanced' },
  ],
  monthly_trend: [
    { month: '2025-12', sold: 71, avg_price: 962000, avg_dom: 24, avg_ppsf: 712 },
    { month: '2026-01', sold: 64, avg_price: 971000, avg_dom: 26, avg_ppsf: 718 },
    { month: '2026-02', sold: 78, avg_price: 985000, avg_dom: 22, avg_ppsf: 725 },
    { month: '2026-03', sold: 92, avg_price: 1003000, avg_dom: 19, avg_ppsf: 738 },
    { month: '2026-04', sold: 104, avg_price: 1018000, avg_dom: 17, avg_ppsf: 749 },
    { month: '2026-05', sold: 87, avg_price: 998000, avg_dom: 18, avg_ppsf: 744 },
  ],
  monthly_trend_by_type: [
    { month: '2025-12', apartment: 631000, townhouse: 1021000, house: 1762000, apartment_sold: 38, townhouse_sold: 14, house_sold: 9, apartment_dom: 22, townhouse_dom: 19, house_dom: 28, apartment_ppsf: 698, townhouse_ppsf: 572, house_ppsf: 418 },
    { month: '2026-01', apartment: 638000, townhouse: 1029000, house: 1771000, apartment_sold: 35, townhouse_sold: 12, house_sold: 8, apartment_dom: 25, townhouse_dom: 21, house_dom: 30, apartment_ppsf: 705, townhouse_ppsf: 578, house_ppsf: 422 },
    { month: '2026-02', apartment: 644000, townhouse: 1038000, house: 1785000, apartment_sold: 42, townhouse_sold: 16, house_sold: 10, apartment_dom: 21, townhouse_dom: 18, house_dom: 26, apartment_ppsf: 712, townhouse_ppsf: 585, house_ppsf: 428 },
    { month: '2026-03', apartment: 649000, townhouse: 1047000, house: 1798000, apartment_sold: 51, townhouse_sold: 20, house_sold: 13, apartment_dom: 18, townhouse_dom: 15, house_dom: 22, apartment_ppsf: 719, townhouse_ppsf: 591, house_ppsf: 435 },
    { month: '2026-04', apartment: 655000, townhouse: 1052000, house: 1812000, apartment_sold: 58, townhouse_sold: 22, house_sold: 14, apartment_dom: 16, townhouse_dom: 14, house_dom: 20, apartment_ppsf: 725, townhouse_ppsf: 596, house_ppsf: 440 },
    { month: '2026-05', apartment: 642000, townhouse: 1045000, house: 1789000, apartment_sold: 48, townhouse_sold: 18, house_sold: 11, apartment_dom: 17, townhouse_dom: 15, house_dom: 23, apartment_ppsf: 718, townhouse_ppsf: 590, house_ppsf: 432 },
  ],
}

/**
 * The agent this fallback content actually describes. Everything in this file - name,
 * bio, service area, privacy policy, terms - is Randy's, so it may only ever be served
 * on his site. getPage() checks this before falling back; serving it to another agent
 * publishes his identity on their domain.
 */
export const FALLBACK_AGENT_SLUG = 'randy'

export const FALLBACK_PAGES: AgentPage[] = [
  {
    slug: 'home',
    title: 'South Surrey & White Rock Real Estate',
    subtitle: 'Local expertise. Real data. Straight answers.',
    hero_image_url: null,
    body: null,
    blocks: [],
    cta_label: 'Book a Consultation',
    cta_url: '/contact',
    meta_title: 'South Surrey & White Rock Real Estate | Randy Dyck',
    meta_description: 'Search South Surrey, White Rock and Cloverdale homes, condos and townhomes. Local market data, sold history and expert guidance from Randy Dyck.',
  },
  {
    slug: 'buyers',
    title: 'Buying a Home',
    subtitle: 'A clear path from search to keys.',
    hero_image_url: null,
    body: null,
    blocks: [],
    cta_label: 'Start Your Search',
    cta_url: '/homes-for-sale',
    meta_title: 'Buying a Home in South Surrey & White Rock | Randy Dyck',
    meta_description: 'A step-by-step home buying guide for South Surrey, White Rock and Cloverdale. Pre-approval, neighbourhood selection, offers and negotiation with Randy Dyck.',
  },
  {
    slug: 'sellers',
    title: 'Selling Your Home',
    subtitle: 'Priced right. Marketed hard. Sold.',
    hero_image_url: null,
    body: null,
    blocks: [],
    cta_label: 'Get a Home Evaluation',
    cta_url: '/contact',
    meta_title: 'Sell Your Home in South Surrey & White Rock | Randy Dyck',
    meta_description: 'Sell your South Surrey, White Rock or Cloverdale home for top dollar. Accurate pricing, professional marketing and expert negotiation from Randy Dyck.',
  },
  {
    slug: 'about',
    title: 'About Randy Dyck',
    subtitle: 'Two decades serving the communities he lives in.',
    hero_image_url: null,
    body: null,
    blocks: [],
    cta_label: null,
    cta_url: null,
    meta_title: 'About Randy Dyck | South Surrey & White Rock Realtor',
    meta_description: 'Meet Randy Dyck — a RE/MAX award-winning realtor with over 20 years of experience in South Surrey, White Rock and Cloverdale real estate.',
  },
  {
    slug: 'privacy',
    title: 'Privacy Policy',
    subtitle: null,
    hero_image_url: null,
    body: null,
    blocks: [
      { type: 'text', content: 'Last updated: June 1, 2026' },
      { type: 'text', content: 'Randy Dyck Real Estate ("we", "us", or "our") is committed to protecting your personal information. This Privacy Policy explains what information we collect, how we use it, and your rights under applicable British Columbia and Canadian privacy law, including the Personal Information Protection Act (PIPA) and the Personal Information Protection and Electronic Documents Act (PIPEDA).' },
      { type: 'heading', level: 2, content: 'Information We Collect' },
      { type: 'text', content: 'We may collect personal information when you contact us, register on the site, save or favourite listings, or sign up for market reports. This may include your name, email address, phone number, and any details you voluntarily provide in contact or inquiry forms.' },
      { type: 'text', content: 'We also collect non-personal information automatically when you visit this site, including your IP address, browser type, pages viewed, and referring URL. This information is used to improve the site and is not linked to your identity.' },
      { type: 'heading', level: 2, content: 'MLS® Data' },
      { type: 'text', content: 'Listing data displayed on this site is provided under licence from the Greater Vancouver REALTORS® (GVR) and the Fraser Valley Real Estate Board (FVREB) through their Multiple Listing Service® (MLS®) system. This data is provided for informational purposes only and may not be reproduced, distributed, or used for commercial purposes without prior written consent. All data is subject to errors and omissions.' },
      { type: 'heading', level: 2, content: 'FINTRAC Obligations' },
      { type: 'text', content: 'As a licensed real estate professional in British Columbia, we are required by the Proceeds of Crime (Money Laundering) and Terrorist Financing Act (PCMLTFA) to verify the identity of clients and report certain transactions to the Financial Transactions and Reports Analysis Centre of Canada (FINTRAC). Personal information collected for these purposes is handled strictly in accordance with federal requirements and is not used for marketing.' },
      { type: 'heading', level: 2, content: 'How We Use Your Information' },
      { type: 'list', items: [
        'To respond to your inquiries and provide real estate services',
        'To send you property updates, market reports, or newsletters (with your consent)',
        'To fulfil FINTRAC identity verification requirements',
        'To improve the functionality and content of this website',
        'To comply with legal obligations',
      ]},
      { type: 'heading', level: 2, content: 'Cookies and Analytics' },
      { type: 'text', content: 'This site uses cookies and similar tracking technologies to improve your browsing experience. We may use Google Analytics (GA4) to understand how visitors interact with the site. Google Analytics collects anonymized data such as pages visited and session duration. You can opt out of Google Analytics tracking by installing the Google Analytics Opt-out Browser Add-on.' },
      { type: 'text', content: 'We may also use the Facebook Pixel to measure the effectiveness of advertising. No personally identifiable information is sent to Facebook via this technology.' },
      { type: 'heading', level: 2, content: 'Third-Party Services' },
      { type: 'text', content: 'We use third-party services to operate this site, including hosting providers, email delivery services, and analytics platforms. These providers are contractually obligated to protect your information and may not use it for any purpose other than providing services to us.' },
      { type: 'heading', level: 2, content: 'Data Retention' },
      { type: 'text', content: 'We retain personal information only as long as necessary to fulfil the purposes for which it was collected, or as required by law. Contact and inquiry records are typically retained for seven years in accordance with real estate licensing requirements in British Columbia.' },
      { type: 'heading', level: 2, content: 'Your Rights' },
      { type: 'text', content: 'You have the right to access, correct, or request deletion of your personal information. To make a request, or to withdraw consent to the use of your information, please contact us at the details below. We will respond within 30 days.' },
      { type: 'heading', level: 2, content: 'Contact Us' },
      { type: 'text', content: 'For privacy-related inquiries or to exercise your rights, please contact Randy Dyck at 604-807-4366 or through the contact form on this website. Our office is located in South Surrey, British Columbia.' },
    ],
    cta_label: null,
    cta_url: null,
    meta_title: 'Privacy Policy | Randy Dyck Real Estate',
    meta_description: 'Privacy Policy for Randy Dyck Real Estate. Learn how we collect, use, and protect your personal information in compliance with BC and Canadian privacy law.',
  },
  {
    slug: 'terms',
    title: 'Terms of Use',
    subtitle: null,
    hero_image_url: null,
    body: null,
    blocks: [
      { type: 'text', content: 'Last updated: June 1, 2026' },
      { type: 'text', content: 'By accessing or using this website (the "Site"), you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, please do not use this Site.' },
      { type: 'heading', level: 2, content: 'Acceptance of Terms' },
      { type: 'text', content: 'These Terms of Use constitute a legally binding agreement between you and Randy Dyck Real Estate. We reserve the right to update these terms at any time. Continued use of the Site after any changes constitutes your acceptance of the revised terms.' },
      { type: 'heading', level: 2, content: 'MLS® Listing Data — Licence Notice' },
      { type: 'text', content: 'Listing information displayed on this Site is provided under licence from the Greater Vancouver REALTORS® (GVR) and the Fraser Valley Real Estate Board (FVREB) through their Multiple Listing Service® (MLS®) system. The data is intended for informational purposes only and does not constitute an offer to sell or a solicitation of an offer to buy any property.' },
      { type: 'text', content: 'MLS®, REALTOR®, and the associated logos are trademarks of the Canadian Real Estate Association (CREA). Used under licence.' },
      { type: 'heading', level: 2, content: 'No Warranty on Listing Accuracy' },
      { type: 'text', content: 'While we make reasonable efforts to ensure listing information is current and accurate, we do not warrant or guarantee the accuracy, completeness, or timeliness of any information on this Site. Listing data may contain errors and omissions (E.&O.E.). You should independently verify all information before relying on it for any purchase, sale, or investment decision.' },
      { type: 'heading', level: 2, content: 'Limitation of Liability' },
      { type: 'text', content: 'To the fullest extent permitted by applicable law, Randy Dyck Real Estate shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of, or inability to use, this Site or its content — including but not limited to losses arising from reliance on listing data, market information, or any communications made through the Site.' },
      { type: 'heading', level: 2, content: 'Prohibited Uses' },
      { type: 'list', items: [
        'Scraping, crawling, or harvesting listing data or contact information for commercial use',
        'Reproducing or redistributing MLS® data without written consent from the applicable board',
        'Using the Site for any unlawful purpose or in violation of applicable regulations',
        'Submitting false or misleading information through any form on the Site',
        'Attempting to gain unauthorized access to any part of the Site or its systems',
      ]},
      { type: 'heading', level: 2, content: 'Intellectual Property' },
      { type: 'text', content: 'All content on this Site — including text, images, graphics, and branding — is the property of Randy Dyck Real Estate or its licensors and is protected by Canadian copyright law. You may not reproduce, modify, or distribute any content without prior written permission.' },
      { type: 'heading', level: 2, content: 'Links to Third-Party Sites' },
      { type: 'text', content: 'This Site may contain links to third-party websites. These links are provided for your convenience only. We do not endorse, control, or assume responsibility for the content or privacy practices of any third-party site. Accessing linked sites is at your own risk.' },
      { type: 'heading', level: 2, content: 'Governing Law' },
      { type: 'text', content: 'These Terms of Use are governed by and construed in accordance with the laws of the Province of British Columbia and the applicable federal laws of Canada. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts of British Columbia.' },
      { type: 'heading', level: 2, content: 'Contact Us' },
      { type: 'text', content: 'If you have questions about these Terms of Use, please contact us at 604-807-4366 or through the contact form on this website.' },
    ],
    cta_label: null,
    cta_url: null,
    meta_title: 'Terms of Use | Randy Dyck Real Estate',
    meta_description: 'Terms of Use for the Randy Dyck Real Estate website. Covers MLS data licence, no-warranty notice, limitation of liability, and governing law (British Columbia).',
  },
]

export const FALLBACK_AWARDS: AgentAward[] = [
  { id: 1, title: 'RE/MAX Diamond Award', organization: 'RE/MAX', year: '2023', logo_url: null, description: 'Awarded to the top-producing RE/MAX agents and teams.' },
  { id: 2, title: 'RE/MAX Hall of Fame', organization: 'RE/MAX', year: '2018', logo_url: null, description: 'Recognizes agents for outstanding career sales achievement.' },
  { id: 3, title: 'RE/MAX Lifetime Achievement', organization: 'RE/MAX', year: '2021', logo_url: null, description: 'Honours long-term commitment and production excellence.' },
  { id: 4, title: 'Medallion Club Member', organization: 'Greater Vancouver REALTORS', year: '2023', logo_url: null, description: 'Top 10% of realtors in the Greater Vancouver board.' },
]

export const FALLBACK_MEDIA: AgentMedia[] = [
  { id: 1, type: 'headshot', collection: 'profile', url: '/storage/agents/randy_dyck_2026.webp', thumbnail_url: null, caption: 'Randy Dyck', alt: 'Randy Dyck, Exp Realty' },
]

export const FALLBACK_NEWS: NewsPost[] = [
  {
    id: 1,
    slug: 'south-surrey-market-update-spring-2026',
    title: 'South Surrey & White Rock Market Update — Spring 2026',
    excerpt: 'After a quieter winter, sales activity in South Surrey and White Rock picked up sharply in March. Here\'s what the data shows and what it means for buyers and sellers heading into summer.',
    body: 'After a quieter winter, sales activity in South Surrey and White Rock picked up sharply in March.\n\n## What the Numbers Show\n\nSales volume in March was up 18% compared to February, with townhouses and detached homes leading the rebound. Apartment sales remained steady.\n\n## What It Means for Sellers\n\nIf you have been waiting for the right time to list, the spring market is here. Inventory remains below historical averages and well-priced homes are moving quickly.\n\n## What It Means for Buyers\n\nAct decisively. The window between listing and multiple offers has shortened considerably. Pre-approval is essential — you need to be ready to write when the right home appears.',
    photo_url: null,
    published_at: '2026-04-02',
    category: 'Market Update',
    tags: ['South Surrey', 'White Rock', 'Market Report', 'Spring 2026'],
  },
  {
    id: 2,
    slug: 'grandview-heights-neighbourhood-guide',
    title: 'Grandview Heights: The Neighbourhood Guide Buyers Actually Need',
    excerpt: 'Grandview Heights has quietly become one of the most sought-after master-planned communities in South Surrey. Here\'s the full picture — the good, the tradeoffs and what to look for.',
    body: 'Grandview Heights has quietly become one of the most sought-after master-planned communities in South Surrey.\n\n## Why Buyers Are Moving Here\n\nNew construction, excellent school catchments and a genuine sense of community draw young families consistently. Prices are slightly below Morgan Creek for comparable product.\n\n## The Tradeoffs\n\nLimited walkability and car-dependency are real. If you need to walk to a coffee shop or commute without a car, this is not the neighbourhood.\n\n## What to Watch For\n\nStrata documents matter a lot here — many buildings are relatively new and depreciation reserves vary significantly. Read them before removing subjects.',
    photo_url: null,
    published_at: '2026-03-14',
    category: 'Neighbourhood Guide',
    tags: ['Grandview Heights', 'South Surrey', 'Neighbourhood', 'Buyers'],
  },
  {
    id: 3,
    slug: 'buying-vs-renting-2026',
    title: 'Buying vs. Renting in South Surrey — An Honest 2026 Analysis',
    excerpt: 'The buy vs. rent debate gets more complicated every year. Here\'s a straight look at the math for South Surrey and White Rock in 2026 — no cheerleading, no alarmism.',
    body: null,
    photo_url: null,
    published_at: '2026-02-20',
    category: 'Analysis',
    tags: ['Buying', 'Renting', 'Analysis', '2026'],
  },
]

export const FALLBACK_TEAM: TeamMember[] = [
  {
    id: 1,
    name: 'Randy Dyck',
    role: 'Lead Agent · REALTOR®',
    photo_url: 'frontend/images/teamagents/randy_dyck.jpg',
    bio: 'With over 18 years specializing in South Surrey and White Rock, Randy has helped 340+ families buy and sell with confidence. Known for his data-driven approach and no-pressure style, Randy gives you real market intelligence so you can make smart decisions.',
    phone: '604-807-4366',
    email: 'randy@randydyck.com',
    license: 'R4568290',
  },
]

const FALLBACK_MONTHLY_TREND = [
  { month: '2025-12', sold: 71, avg_price: 962000, avg_dom: 24, avg_ppsf: 712 },
  { month: '2026-01', sold: 64, avg_price: 971000, avg_dom: 26, avg_ppsf: 718 },
  { month: '2026-02', sold: 78, avg_price: 985000, avg_dom: 22, avg_ppsf: 725 },
  { month: '2026-03', sold: 92, avg_price: 1003000, avg_dom: 19, avg_ppsf: 738 },
  { month: '2026-04', sold: 104, avg_price: 1018000, avg_dom: 17, avg_ppsf: 749 },
  { month: '2026-05', sold: 87, avg_price: 998000, avg_dom: 18, avg_ppsf: 744 },
]

export const FALLBACK_NEIGHBOURHOOD_DETAILS: Record<string, NeighbourhoodDetail> = {
  'south-surrey-white-rock': {
    name: 'South Surrey White Rock',
    city: 'Surrey',
    subarea: 'South Surrey White Rock',
    description: 'South Surrey White Rock is one of Metro Vancouver\'s most sought-after residential areas, stretching from the US border at White Rock north through established family communities like Morgan Creek, Ocean Park, and Grandview Heights. Known for its ocean views, mature neighbourhoods, and access to top schools, it attracts families, professionals, and retirees alike.',
    widget: { subarea: 'South Surrey White Rock', city: 'Surrey', active: 184, sold_30d: 87, avg_sold_price: 998000, avg_dom: 18, absorption_rate: 47.3, market_type: 'sellers' },
    monthly_trend: FALLBACK_MONTHLY_TREND,
    active: FALLBACK_LISTINGS.slice(0, 6),
    recent_sold: FALLBACK_SOLD_LISTINGS,
  },
  'grandview-heights': {
    name: 'Grandview Heights',
    city: 'Surrey',
    subarea: 'Grandview Heights',
    description: 'A master-planned community in South Surrey known for new construction, excellent school catchments, and a genuine sense of community.',
    widget: { subarea: 'Grandview Heights', city: 'Surrey', active: 56, sold_30d: 28, avg_sold_price: 875000, avg_dom: 21, absorption_rate: 50.0, market_type: 'sellers' },
    monthly_trend: FALLBACK_MONTHLY_TREND.map(p => ({ ...p, avg_price: Math.round(p.avg_price * 0.88) })),
    active: FALLBACK_LISTINGS.slice(0, 3),
    recent_sold: FALLBACK_SOLD_LISTINGS.slice(0, 3),
  },
  'morgan-creek': {
    name: 'Morgan Creek',
    city: 'Surrey',
    subarea: 'Morgan Creek',
    description: 'One of South Surrey\'s most desirable enclaves, Morgan Creek offers upscale detached homes surrounding the Morgan Creek Golf Course.',
    widget: { subarea: 'Morgan Creek', city: 'Surrey', active: 38, sold_30d: 18, avg_sold_price: 1045000, avg_dom: 13, absorption_rate: 47.4, market_type: 'strong-sellers' },
    monthly_trend: FALLBACK_MONTHLY_TREND.map(p => ({ ...p, avg_price: Math.round(p.avg_price * 1.05) })),
    active: FALLBACK_LISTINGS.slice(0, 3),
    recent_sold: FALLBACK_SOLD_LISTINGS.slice(0, 4),
  },
  'cloverdale-bc': {
    name: 'Cloverdale',
    city: 'Surrey',
    subarea: 'Cloverdale BC',
    description: 'Cloverdale is a charming historic community offering affordable housing options in Surrey, popular with first-time buyers and young families.',
    widget: { subarea: 'Cloverdale BC', city: 'Surrey', active: 47, sold_30d: 21, avg_sold_price: 820000, avg_dom: 22, absorption_rate: 44.7, market_type: 'balanced' },
    monthly_trend: FALLBACK_MONTHLY_TREND.map(p => ({ ...p, avg_price: Math.round(p.avg_price * 0.82) })),
    active: FALLBACK_LISTINGS.slice(0, 4),
    recent_sold: FALLBACK_SOLD_LISTINGS.slice(0, 3),
  },
  'white-rock': {
    name: 'White Rock',
    city: 'White Rock',
    subarea: null,
    description: 'White Rock is a seaside city known for its pier, oceanfront promenade, and relaxed lifestyle — attracting retirees and buyers seeking waterfront proximity.',
    widget: { subarea: 'White Rock', city: 'White Rock', active: 63, sold_30d: 24, avg_sold_price: 780000, avg_dom: 19, absorption_rate: 38.1, market_type: 'balanced' },
    monthly_trend: FALLBACK_MONTHLY_TREND.map(p => ({ ...p, avg_price: Math.round(p.avg_price * 0.78) })),
    active: FALLBACK_LISTINGS.slice(3, 6),
    recent_sold: FALLBACK_SOLD_LISTINGS.slice(2, 5),
  },
}

export const FALLBACK_OPEN_HOUSES: OpenHouseItem[] = []

export const FALLBACK_PRICE_MATRIX: PriceMatrix = {
  generated_at: new Date().toISOString(),
  rows: [
    { type: 'Apartment', beds: 1, avg_price: 548000, avg_ppsf: 820, count: 41, avg_dom: 15 },
    { type: 'Apartment', beds: 2, avg_price: 698000, avg_ppsf: 752, count: 63, avg_dom: 14 },
    { type: 'Apartment', beds: 3, avg_price: 889000, avg_ppsf: 721, count: 18, avg_dom: 19 },
    { type: 'Apartment', beds: 4, avg_price: 1120000, avg_ppsf: 690, count: 5, avg_dom: 22 },
    { type: 'Townhouse', beds: 1, avg_price: 699000, avg_ppsf: 698, count: 8, avg_dom: 12 },
    { type: 'Townhouse', beds: 2, avg_price: 879000, avg_ppsf: 672, count: 31, avg_dom: 13 },
    { type: 'Townhouse', beds: 3, avg_price: 1079000, avg_ppsf: 645, count: 44, avg_dom: 16 },
    { type: 'Townhouse', beds: 4, avg_price: 1249000, avg_ppsf: 612, count: 14, avg_dom: 18 },
    { type: 'House', beds: 2, avg_price: 1189000, avg_ppsf: 580, count: 6, avg_dom: 28 },
    { type: 'House', beds: 3, avg_price: 1489000, avg_ppsf: 558, count: 22, avg_dom: 24 },
    { type: 'House', beds: 4, avg_price: 1789000, avg_ppsf: 532, count: 31, avg_dom: 27 },
    { type: 'House', beds: 4, avg_price: 2249000, avg_ppsf: 498, count: 18, avg_dom: 32 },
  ],
}
